# Generated by Django 5.0.4 on 2025-04-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
